### ISSUE TITLE
Error: Unsupported platform: Darwin arm64

### ISSUE THREAD

**Issue by JSHan94** [dsrvlabs/wds-code-remix#3]
Problem 
- Current main branch doesn't support M1 Mac OS
- When i run `npm install`, the result looks like
```bash
npm ERR! code 1
npm ERR! path /Users/jungsuhan/workspace/wds-code-remix/node_modules/near-vm
npm ERR! command failed
npm ERR! command sh -c -- node ./install.js
npm ERR! /Users/jungsuhan/workspace/wds-code-remix/node_modules/near-vm/getBinary.js:17
npm ERR!     throw new Error(`Unsupported platform: ${type} ${arch}`);
npm ERR!     ^
npm ERR! 
npm ERR! Error: Unsupported platform: Darwin arm64
npm ERR!     at getPlatform (/Users/jungsuhan/workspace/wds-code-remix/node_modules/near-vm/getBinary.js:17:11)
npm ERR!     at getBinary (/Users/jungsuhan/workspace/wds-code-remix/node_modules/near-vm/getBinary.js:21:22)
npm ERR!     at Object.<anonymous> (/Users/jungsuhan/workspace/wds-code-remix/node_modules/near-vm/install.js:2:1)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1218:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1081:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:922:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
npm ERR!     at node:internal/main/run_main_module:23:47
npm ERR! 
npm ERR! Node.js v19.2.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jungsuhan/.npm/_logs/2023-03-13T05_22_30_301Z-debug-0.log
```

**Comment by JSHan94** [comment]
One more question, how can i test this project in local evironment? Is there any tutorial for this?
